<?php
// Set error reporting high during development
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// 1. START SESSION
session_start();

// CRITICAL: Ensure this path matches the simple path used in offline-quiz.php
// 2. CHECK AND INCLUDE BACKEND FILES SAFELY
$controller_path = '../../../../Controller/quiz-controller.php'; // <--- Check this path!
$has_backend = false;
$error_output = '';

if (file_exists($controller_path)) {
    try {
        require_once $controller_path; 
        $has_backend = true;
    } catch (Exception $e) {
        $_SESSION['error'] = "FATAL ERROR: Controller failed to load. Path: " . htmlspecialchars($controller_path) . " | Error: " . $e->getMessage();
        header('Location: offline-quiz.php');
        exit();
    }
} else {
    $_SESSION['error'] = "FATAL ERROR: Controller file not found at path: " . htmlspecialchars($controller_path);
    header('Location: offline-quiz.php');
    exit();
}
// If we reach here, the backend is loaded.

// 3. PROCESS NEW GAME SUBMISSION (Only if POST data is present)
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['selected_categories'])) {
    // --- Validation and Setup Logic ---
    $team1Name = htmlspecialchars(trim($_POST['team1_name']));
    $team2Name = htmlspecialchars(trim($_POST['team2_name']));
    $rawCategories = trim($_POST['selected_categories']);
    $selectedCategories = array_filter(explode(',', $rawCategories)); 

    if (empty($team1Name) || empty($team2Name) || count($selectedCategories) !== 4) {
        $_SESSION['error'] = "Error: Invalid team names or incorrect number of categories selected.";
        header('Location: offline-quiz.php');
        exit();
    }
    
    $gameData = [
        'teams' => [ 1 => ['name' => $team1Name, 'score' => 0], 2 => ['name' => $team2Name, 'score' => 0], ],
        'current_turn' => 1, 'quizzes' => [], 'category_names' => $selectedCategories, 
    ];

    try {
        $quizController = new QuizController();
        $allQuizzes = $quizController->listQuizzes(); 

        // Add the categoryDetails array here or include it from a separate config file
        $categoryDetails = [ 
            "environment" => ["icon" => "fas fa-leaf", "color" => "#38c172"],
            "science" => ["icon" => "fas fa-flask", "color" => "#1b6f9a"],
            "history" => ["icon" => "fas fa-scroll", "color" => "#e3342f"], 
            "social-impact" => ["icon" => "fas fa-handshake", "color" => "#f6993f"],
            "personal-growth" => ["icon" => "fas fa-seedling", "color" => "#6574cd"],
            "general-knowledge" => ["icon" => "fas fa-lightbulb", "color" => "#f7c35f"],
            "technology" => ["icon" => "fas fa-microchip", "color" => "#8338ec"],
            "arts-culture" => ["icon" => "fas fa-palette", "color" => "#d5573b"],
            // Make sure these keys match the slugs from offline-quiz.php
        ];


        foreach ($selectedCategories as $categorySlug) {
            $availableQuizzes = array_filter($allQuizzes, function($quiz) use ($categorySlug) {
                // IMPORTANT: Normalizing the category name to match the slug generated by JS in offline-quiz.php
                // The JS uses a pattern that removes non-alphanumeric/spaces, replaces spaces with '-', and lowercases.
                $cleanCategoryName = preg_replace('/[^A-Za-z0-9 ]/', '', $quiz->getCategorie());
                $quizCategorySlug = strtolower(str_replace(' ', '-', trim($cleanCategoryName)));
                return $quizCategorySlug === $categorySlug;
            });
            $availableQuizzes = array_values($availableQuizzes); 
            
            if (count($availableQuizzes) < 2) {
                // Throw an exception to halt the setup process
                throw new Exception("Not enough quizzes (needs 2, found " . count($availableQuizzes) . ") for category: " . htmlspecialchars(ucwords(str_replace('-', ' ', $categorySlug))));
            }

            shuffle($availableQuizzes);
            $quiz1 = $availableQuizzes[0]; 
            $quiz2 = $availableQuizzes[1]; 
            
            $gameData['quizzes'][$categorySlug] = [
                'q1_id' => $quiz1->getIdQuiz(), 'q1_title' => $quiz1->getTitre(), 'q1_points' => $quiz1->getPoints(), 'q1_status' => 'available', 
                'q2_id' => $quiz2->getIdQuiz(), 'q2_title' => $quiz2->getTitre(), 'q2_points' => $quiz2->getPoints(), 'q2_status' => 'available',
                'category_full_name' => $quiz1->getCategorie(),
            ];
        }

        // D. Save the new game state on success
        $_SESSION['offline_game'] = $gameData;
        unset($_SESSION['error']); 
        // DO NOT REDIRECT HERE IF THE INTENTION IS TO DISPLAY THE GAME BOARD BELOW
        // A successful POST submission to the same page that then displays its content is fine.
        // If you redirect, you lose the POST data and the game logic must rely entirely on $_SESSION.
        // For simplicity, we remove the redirect and proceed to step 5.

    } catch (Exception $e) {
        $_SESSION['error'] = "Game Setup Failed: " . $e->getMessage();
        header('Location: offline-quiz.php');
        exit();
    }
} elseif (!isset($_SESSION['offline_game'])) {
    // 4. DISPLAY ERROR IF NO GAME IN SESSION
    http_response_code(404); // Set a 'Not Found' status
    echo <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Game Not Started</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/css/vendor/bootstrap.min.css">
    <style>
        body {
            background-color: #005248;
            color: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            font-family: 'Gordita', sans-serif;
            text-align: center;
        }
        .error-container {
            background: rgba(255, 255, 255, 0.08);
            backdrop-filter: blur(15px);
            border: 2px solid rgba(255, 255, 255, 0.3);
            border-radius: 25px;
            padding: 40px;
            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.5);
        }
        h1 {
            font-size: 2.5rem;
            color: #FFBB28;
            margin-bottom: 20px;
        }
        p {
            font-size: 1.2rem;
            margin-bottom: 30px;
        }
        .btn-start-new-game {
            background-color: #00C49F;
            color: #000;
            font-weight: 700;
            padding: 15px 30px;
            border-radius: 10px;
            text-decoration: none;
            transition: all 0.3s ease;
        }
        .btn-start-new-game:hover {
            background-color: #FFBB28;
            transform: translateY(-3px);
        }
    </style>
</head>
<body>
    <div class="error-container">
        <h1><i class="fas fa-ghost"></i> Oops! No Game Found</h1>
        <p>It seems you've landed here without setting up a battle. Every great quest needs a beginning!</p>
        <a href="offline-quiz.php" class="btn-start-new-game">
            <i class="fas fa-hat-wizard"></i> Click Here to Start a New Game
        </a>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"></script>
</body>
</html>
HTML;
    exit();
}

// 5. DEFINE DISPLAY VARIABLES (CRITICAL FIX)
// If we reach this point, $_SESSION['offline_game'] is set, either from the current POST 
// submission process above, or from a previous state.

$gameData = $_SESSION['offline_game'];
$team1 = $gameData['teams'][1];
$team2 = $gameData['teams'][2];
$currentTurn = $gameData['current_turn'];
$quizzes = $gameData['quizzes'];

// Redefine/Ensure $categoryDetails is available for the display part
// This MUST match the slug keys (lowercase-hyphenated)
$categoryDetails = [ 
    "environment" => ["icon" => "fas fa-leaf", "color" => "#38c172"],
    "science" => ["icon" => "fas fa-flask", "color" => "#1b6f9a"],
    "history" => ["icon" => "fas fa-scroll", "color" => "#e3342f"], 
    "social-impact" => ["icon" => "fas fa-handshake", "color" => "#f6993f"],
    "personal-growth" => ["icon" => "fas fa-seedling", "color" => "#6574cd"],
    "general-knowledge" => ["icon" => "fas fa-lightbulb", "color" => "#f7c35f"],
    "technology" => ["icon" => "fas fa-microchip", "color" => "#8338ec"],
    "arts-culture" => ["icon" => "fas fa-palette", "color" => "#d5573b"],
];

// --- GAME ALREADY INITIALIZED (The display logic remains unchanged) ---
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Offline Battle: Choose Category</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/x-icon" href="assets/images/fab-icon.png">
    <link rel="stylesheet" href="assets/css/plugins/gordita.css">
    <link rel="stylesheet" href="assets/css/plugins/fontawesome-pro-icons.css">
    <link rel="stylesheet" href="assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <style>
        /* Inherited Styles */
        body.rt_bg-secondary {
            background: linear-gradient(135deg, #005248, #00c49f, #00796b);
            background-size: 400% 400%;
            animation: moveGradient 20s ease infinite;
        }
        @keyframes moveGradient { 0% { background-position: 0% 50%; } 50% { background-position: 100% 50%; } 100% { background-position: 0% 50%; } }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(40px); } to { opacity: 1; transform: translateY(0); } }

        /* Game Container */
        .game-container {
            background: rgba(255, 255, 255, 0.08);
            backdrop-filter: blur(25px);
            border: 2px solid rgba(255, 255, 255, 0.3);
            border-radius: 40px;
            padding: 60px 50px;
            box-shadow: 0 15px 60px rgba(0, 0, 0, 0.6);
            max-width: 1200px;
            margin: 80px auto;
            color: #fff;
            animation: fadeIn 0.8s cubic-bezier(0.2, 0.8, 0.2, 1) forwards;
        }

        /* Title/Turn Display */
        .turn-display {
            font-size: 2.5rem;
            font-weight: 800;
            color: #FFBB28;
            text-align: center;
            margin-bottom: 40px;
            text-shadow: 0 0 10px rgba(255, 187, 40, 0.5);
        }

        /* Scoreboard */
        .scoreboard {
            background: rgba(0, 0, 0, 0.3);
            border-radius: 15px;
            padding: 20px 30px;
            margin-bottom: 50px;
            display: flex;
            justify-content: space-around;
        }

        .team-score {
            text-align: center;
            padding: 0 20px;
            border-right: 1px dashed rgba(255, 255, 255, 0.3);
        }
        .team-score:last-child {
            border-right: none;
        }

        .team-score h3 {
            font-size: 1.5rem;
            color: #00C49F;
            margin-bottom: 5px;
        }

        .team-score p {
            font-size: 2.5rem;
            font-weight: 700;
            margin: 0;
            color: #fff;
        }

        /* Quiz Cards Grid */
        .quiz-card-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr); /* Two quizzes per category in a row */
            gap: 30px;
            margin-bottom: 50px;
        }

        /* Category Header */
        .category-header {
            grid-column: 1 / -1; /* Spans across both quiz columns */
            text-align: center;
            font-size: 1.8rem;
            font-weight: 700;
            color: #fff;
            padding: 15px 0;
            margin-bottom: 10px;
            border-bottom: 2px solid #00C49F;
            position: relative;
        }
        .category-header i {
            font-size: 2.2rem;
            margin-right: 10px;
        }
        
        /* Individual Quiz Card */
        .quiz-choice-card {
            background: rgba(255, 255, 255, 0.1);
            border: 2px solid rgba(255, 255, 255, 0.3);
            border-radius: 15px;
            padding: 25px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            height: 100%;
            transition: all 0.3s ease;
        }

        .quiz-choice-card.disabled {
            opacity: 0.5;
            cursor: not-allowed;
            background: rgba(0, 0, 0, 0.3);
            box-shadow: none;
        }

        .quiz-choice-card:not(.disabled):hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.4);
            border-color: #FFBB28;
        }

        .quiz-choice-card h4 {
            font-size: 1.4rem;
            font-weight: 600;
            color: #fff;
            margin-bottom: 15px;
        }

        .quiz-choice-card p.points {
            font-size: 1.2rem;
            font-weight: 700;
            color: #FFBB28;
            margin-bottom: 20px;
        }

        .quiz-choice-card .select-btn {
            background-color: #00C49F;
            color: #000;
            font-weight: 700;
            padding: 10px;
            border-radius: 8px;
            text-align: center;
            text-transform: uppercase;
            transition: all 0.2s ease;
        }
        .quiz-choice-card:not(.disabled) .select-btn:hover {
            background-color: #FFBB28;
            color: #000;
        }
    </style>
</head>

<body class="rt_bg-secondary">
    <?php
    // Insert this block right here in offline-quiz.php
    if (isset($_SESSION['error'])) {
        echo '<div class="container mt-5">';
        echo '<div class="alert alert-danger text-center" style="background: rgba(255, 107, 107, 0.9); color: white; border: none; border-radius: 15px; padding: 20px;">';
        echo '<strong>Game Setup Error!</strong><br>' . htmlspecialchars($_SESSION['error']);
        echo '</div></div>';
        unset($_SESSION['error']); // Clear it after display
    }
    ?>

    <div class="bg-animation">
        <div class="blob blob1"></div>
        <div class="blob blob2"></div>
    </div>
    
    <div class="rts-section-gap">
        <div class="container">
            <div class="game-container">
                
                <h2 class="turn-display">
                    <i class="fas fa-bullseye me-2"></i> It's **<?php echo htmlspecialchars($gameData['teams'][$currentTurn]['name']); ?>**'s Turn to Choose!
                </h2>

                <<!-- c:\xampp\htdocs\Projet\View\FRONT OFFICE\PRINCIPAL\genifty-html\start-offline-game.php -->
                
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <title>Zitouna Quests - Game Board</title>
                    <!-- ... vos autres balises meta et link ... -->
                    <link rel="stylesheet" href="assets/css/plugins/gordita.css">
                    <link rel="stylesheet" href="assets/css/vendor/bootstrap.min.css">
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
                
                    <!-- ▼▼▼ COPIEZ ET COLLEZ TOUT LE BLOC STYLE CI-DESSOUS ▼▼▼ -->
                    <style>
                        /* --- Styles Généraux --- */
                        body {
                            background: linear-gradient(135deg, #005248, #00c49f, #00796b);
                            background-size: 400% 400%;
                            animation: moveGradient 20s ease infinite;
                            color: #fff;
                            font-family: 'Gordita', sans-serif;
                            padding-top: 40px;
                            padding-bottom: 60px;
                        }
                
                        @keyframes moveGradient { 
                            0% { background-position: 0% 50%; } 
                            50% { background-position: 100% 50%; } 
                            100% { background-position: 0% 50%; } 
                        }
                
                        .game-container {
                            max-width: 1200px;
                            margin: 0 auto;
                            padding: 0 15px;
                        }
                
                        /* --- Titre Principal --- */
                        .game-title {
                            font-size: 3.5rem;
                            font-weight: 800;
                            text-align: center;
                            color: #fff;
                            text-shadow: 0 0 15px rgba(0, 196, 159, 0.6), 0 0 5px rgba(255, 255, 255, 0.5);
                            margin-bottom: 40px;
                        }
                
                        /* --- Tableau des Scores --- */
                        .scoreboard {
                            display: flex;
                            justify-content: space-around;
                            align-items: center;
                            background: rgba(0, 0, 0, 0.3);
                            backdrop-filter: blur(15px);
                            border: 2px solid rgba(255, 255, 255, 0.2);
                            border-radius: 25px;
                            padding: 25px 20px;
                            margin-bottom: 50px;
                            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.4);
                        }
                
                        .team-score {
                            text-align: center;
                            flex: 1;
                        }
                
                        .team-score .team-name {
                            font-size: 1.8rem;
                            font-weight: 700;
                            margin-bottom: 10px;
                            color: #fff;
                        }
                
                        .team-score .score {
                            font-size: 3rem;
                            font-weight: 800;
                            color: #FFBB28; /* Couleur or pour le score */
                            line-height: 1;
                            text-shadow: 0 0 10px rgba(255, 187, 40, 0.7);
                        }
                
                        /* --- Indicateur de Tour --- */
                        .turn-indicator {
                            font-size: 1.3rem;
                            font-weight: 600;
                            padding: 12px 25px;
                            background: #00C49F;
                            color: #fff;
                            border-radius: 50px;
                            border: 2px solid #fff;
                            box-shadow: 0 0 20px rgba(0, 196, 159, 0.8);
                            white-space: nowrap;
                        }
                
                        /* --- Plateau de Jeu --- */
                        .game-board {
                            display: grid;
                            grid-template-columns: repeat(4, 1fr); /* 4 colonnes pour les catégories */
                            gap: 30px;
                        }
                
                        .category-column {
                            background: rgba(0, 0, 0, 0.2);
                            border: 1px solid rgba(255, 255, 255, 0.15);
                            border-radius: 20px;
                            padding: 20px;
                            text-align: center;
                            transition: all 0.3s ease;
                        }
                        .category-column:hover {
                            transform: translateY(-5px);
                            box-shadow: 0 10px 30px rgba(0,0,0,0.3);
                        }
                
                        .category-header {
                            font-size: 1.7rem;
                            font-weight: 700;
                            color: #FFBB28;
                            padding-bottom: 15px;
                            margin-bottom: 20px;
                            border-bottom: 2px solid rgba(255, 255, 255, 0.2);
                        }
                        .category-header i {
                            margin-right: 10px;
                        }
                
                        /* --- Cartes de Quiz --- */
                        .quiz-card {
                            display: block;
                            background: rgba(255, 255, 255, 0.1);
                            border: 2px solid rgba(255, 255, 255, 0.3);
                            border-radius: 15px;
                            padding: 25px 20px;
                            margin-top: 20px;
                            text-decoration: none;
                            color: #fff;
                            font-size: 1.5rem;
                            font-weight: 700;
                            transition: all 0.3s ease;
                        }
                
                        .quiz-card:hover {
                            background: rgba(0, 196, 159, 0.5);
                            border-color: #00C49F;
                            transform: scale(1.05);
                            box-shadow: 0 0 20px rgba(0, 196, 159, 0.7);
                        }
                
                        /* État désactivé pour les quiz terminés */
                        .quiz-card.disabled {
                            background: rgba(0, 0, 0, 0.5);
                            border-color: rgba(255, 255, 255, 0.1);
                            color: rgba(255, 255, 255, 0.4);
                            cursor: not-allowed;
                            text-decoration: line-through;
                        }
                        .quiz-card.disabled:hover {
                            transform: none;
                            box-shadow: none;
                            background: rgba(0, 0, 0, 0.5);
                            border-color: rgba(255, 255, 255, 0.1);
                        }
                
                        /* --- Styles pour les écrans plus petits --- */
                        @media (max-width: 992px) {
                            .game-board {
                                grid-template-columns: repeat(2, 1fr); /* 2 colonnes sur tablettes */
                            }
                            .game-title {
                                font-size: 2.8rem;
                            }
                        }
                
                        @media (max-width: 768px) {
                            .scoreboard {
                                flex-direction: column;
                                gap: 20px;
                            }
                            .turn-indicator {
                                order: -1; /* Met l'indicateur de tour en haut */
                            }
                        }
                
                        @media (max-width: 576px) {
                            .game-board {
                                grid-template-columns: 1fr; /* 1 colonne sur mobile */
                            }
                            .team-score .team-name { font-size: 1.5rem; }
                            .team-score .score { font-size: 2.5rem; }
                        }
                    </style>
                
                </head>
                <body>
                </body>
                </html>
                <div class="scoreboard">
                    <div class="team-score">
                        <h3><i class="fas fa-shield-alt me-1"></i> <?php echo htmlspecialchars($team1['name']); ?></h3>
                        <p><?php echo htmlspecialchars($team1['score']); ?> <small>pts</small></p>
                    </div>
                    <div class="team-score">
                         <h3 style="border-left: 1px dashed rgba(255, 255, 255, 0.3); padding-left: 20px;"><i class="fas fa-dragon me-1"></i> <?php echo htmlspecialchars($team2['name']); ?></h3>
                        <p><?php echo htmlspecialchars($team2['score']); ?> <small>pts</small></p>
                    </div>
                </div>

                <h3 class="text-center mb-4" style="color: #00C49F; font-size: 1.6rem;">Select a Quiz to Attempt</h3>

                <div class="row g-4">
                    <?php foreach ($quizzes as $categorySlug => $catQuizzes): 
                        $details = $categoryDetails[$categorySlug] ?? ["icon" => "fas fa-question-circle", "color" => "#999999"];
                        $categoryIcon = $details['icon'];
                        $categoryColor = $details['color'];
                    ?>
                        <div class="col-lg-6">
                            <div class="quiz-card-grid">
                                <div class="category-header" style="border-color: <?php echo $categoryColor; ?>;">
                                    <i class="<?php echo $categoryIcon; ?>" style="color: <?php echo $categoryColor; ?>;"></i> 
                                    <?php echo htmlspecialchars(ucwords(str_replace('-', ' ', $categorySlug))); ?>
                                </div>

                                <?php for ($i = 1; $i <= 2; $i++): 
                                    $quizId = $catQuizzes['q' . $i . '_id'];
                                    $quizTitle = $catQuizzes['q' . $i . '_title'];
                                    $quizPoints = $catQuizzes['q' . $i . '_points'];
                                    $quizStatus = $catQuizzes['q' . $i . '_status'];
                                    $isDisabled = $quizStatus !== 'available';
                                    $targetFile = $isDisabled ? '#' : 'take-offline-quiz.php?quiz=' . $quizId;
                                ?>
                                    <div class="col-6">
                                        <a href="<?php echo $targetFile; ?>" class="quiz-choice-card <?php echo $isDisabled ? 'disabled' : ''; ?>" style="border-color: <?php echo $categoryColor; ?>;">
                                            <div>
                                                <h4>Quiz #<?php echo $i; ?>: <?php echo $quizTitle; ?></h4>
                                                <p class="points">+<?php echo $quizPoints; ?> Points</p>
                                            </div>
                                            <div class="select-btn" style="background-color: <?php echo $categoryColor; ?>; color: #000;">
                                                <?php echo $isDisabled ? 'Completed' : 'Select'; ?>
                                            </div>
                                        </a>
                                    </div>
                                <?php endfor; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>

                <p class="text-center mt-4" style="color: #eee; font-style: italic;">
                    <i class="fas fa-info-circle me-1"></i> **Game Goal:** Complete all 8 quizzes and finish with the highest score!
                </p>

            </div>
        </div>
    </div>

    <script src="assets/js/vendor/jquery.min.js"></script>
    <script src="assets/js/vendor/bootstrap.min.js"></script>
    </body>
</html>